require: rubocop-rspec

AllCops:
  Exclude:
    - 'gemfiles/**/*'
    - 'vendor/**/*'

# Ruby 3.0: curly braces around last argument has meaning
# See: https://github.com/rubocop/rubocop/issues/7641
Style/BracesAroundHashParameters:
  Enabled: false

Metrics/ClassLength:
  Max: 200

Metrics/ModuleLength:
  Max: 150

Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'spec/support/*'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/**/*_spec.rb'

RSpec/ExpectInHook:
  Enabled: false

RSpec/EmptyLineAfterHook:
  Enabled: false

RSpec/ScatteredSetup:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - cloudtasker.gemspec
    - 'spec/**/*'

Style/Documentation:
  Exclude:
    - 'examples/**/*'
    - 'spec/**/*'

Metrics/ParameterLists:
  CountKeywordArgs: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Exclude:
    - 'examples/**/*'
    - 'spec/integration/**/*'