---
language: ruby
cache: bundler
rvm:
  - 2.5.5
services:
  - redis-server
before_install: gem install bundler -v 2.0.2
before_script: bundle exec rubocop
gemfile:
  - gemfiles/google_cloud_tasks_1.0.gemfile
  - gemfiles/google_cloud_tasks_1.1.gemfile
  - gemfiles/google_cloud_tasks_1.2.gemfile
  - gemfiles/google_cloud_tasks_1.3.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
